const IconListingConfig = {
  site: {
    name: "Icon Listing",
    owner: "IconRealms",
    basePath: "",
    iconPath: "/assets/icon.png",
    discordUrl: "https://discord.gg/fMbfFW7PWX",
    contactEmail: "officialfnaffanstudios@gmail.com",
    footerNotice:
      "This site is not an official Minecraft service and is not approved by or associated with Mojang or Microsoft."
  },
  theme: {
    colors: {
      purple: "#8b5cf6",
      pink: "#ec4899",
      black: "#050509",
      blue: "#38bdf8",
      cyan: "#22d3ee",
      green: "#22c55e",
      amber: "#f59e0b",
      surface: "#101018",
      surfaceSoft: "#171724",
      text: "#f7f7fb",
      muted: "#a6a7b7",
      border: "rgba(255,255,255,.12)"
    }
  },
  api: {
    basePath: "/api",
    useLocalFallback: true,
    requestTimeoutMs: 8000
  },
  admins: {
    users: ["ItzKuroYT"],
    emails: ["isaaccooper926@gmail.com"]
  },
  limits: {
    bannerMaxBytes: 1048576,
    bannerMaxWidth: 468,
    bannerMaxHeight: 60,
    descriptionMinLength: 200,
    tagsMin: 1,
    tagsMax: 7,
    staleServerDeleteDays: 90
  },
  ranking: {
    playerWeight: 1,
    voteWeight: 8,
    sponsoredBoost: 100000
  },
  defaults: {
    javaPort: 25565,
    bedrockPort: 19132
  },
  sponsorship: {
    paypalRequired: true,
    applicationText:
      "To apply for sponsorship, join the Discord server and submit an application. Sponsorships are paid and currently require PayPal.",
    benefits: [
      "Top placement on the homepage.",
      "Top placement on matching tag pages.",
      "Top placement in search results.",
      "Highlighted listing style with a star badge."
    ]
  },
  votifier: {
    enabled: true,
    providerEndpoint: "",
    documentationUrl: "https://github.com/NuVotifier/NuVotifier",
    testUsername: "IconListingTest"
  },
  moderation: {
    replacement: "***",
    blockedWords: [
      "fuck",
      "shit",
      "bitch",
      "asshole",
      "bastard",
      "cunt",
      "dick",
      "pussy",
      "nigger",
      "nigga",
      "faggot",
      "retard",
      "kike",
      "spic",
      "chink",
      "coon",
      "tranny"
    ],
    blockedPatterns: [
      "n[i1!|][gq][gq][e3]r",
      "f[a@]gg[o0]t",
      "r[e3]t[a@]rd"
    ]
  },
  gamemodes: [
    "Survival",
    "Factions",
    "Skyblock",
    "Creative",
    "Anarchy",
    "OneBlock",
    "Economy",
    "PvP",
    "Pixelmon",
    "Lifesteal",
    "KitPvP",
    "Cobblemon",
    "SMP",
    "BoxPvP",
    "Roleplay",
    "Earth",
    "Prison",
    "RPG",
    "Towny",
    "Raiding",
    "Gens",
    "Farming",
    "Vanilla",
    "Minigames",
    "BedWars",
    "Parkour"
  ],
  generalTags: ["Bedrock", "Cross-Play", "Modded", "Whitelist", "New", "Old"],
  countries: [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo",
    "Costa Rica",
    "Cote d'Ivoire",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czechia",
    "Democratic Republic of the Congo",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Korea",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe"
  ],
  seedServers: [],
  sponsoredClients: []
};

if (typeof window !== "undefined") {
  window.ICON_LISTING_CONFIG = IconListingConfig;
}

if (typeof module !== "undefined") {
  module.exports = IconListingConfig;
}
