const IconListingConfig = {
  site: {
    name: "Icon Listing",
    owner: "IconRealms",
    url: "https://icon-listing.vercel.app",
    basePath: "",
    iconPath: "/assets/icon.png",
    discordUrl: "https://discord.gg/fMbfFW7PWX",
    contactEmail: "officialfnaffanstudios@gmail.com",
    footerNotice:
      "This site is not an official Minecraft service and is not approved by or associated with Mojang or Microsoft."
  },
  theme: {
    colors: {
      purple: "#8b5cf6",
      pink: "#ec4899",
      black: "#050509",
      blue: "#38bdf8",
      cyan: "#22d3ee",
      green: "#22c55e",
      amber: "#f59e0b",
      surface: "#101018",
      surfaceSoft: "#171724",
      text: "#f7f7fb",
      muted: "#a6a7b7",
      border: "rgba(255,255,255,.12)"
    }
  },
  api: {
    basePath: "/api",
    productionBasePath: "https://icon-listing.vercel.app/api",
    useLocalFallback: true,
    localFallbackHosts: ["", "localhost", "127.0.0.1"],
    requestTimeoutMs: 8000
  },
  seo: {
    defaultTitle: "Top Minecraft Servers | Best Server List 2026",
    defaultDescription:
      "Find the best Minecraft servers. Filter by Skyblock, Factions, SMP, Lifesteal, Prison, and more. Vote for your favorite server today!",
    keywords: [
      "minecraft servers",
      "minecraft server list",
      "best minecraft servers",
      "minecraft voting",
      "factions servers",
      "lifesteal servers",
      "minecraft server finder",
      "top minecraft servers"
    ],
    pages: {
      home: {
        title: "Top Minecraft Servers | Best Server List 2026",
        description:
          "Find the best Minecraft servers. Filter by Skyblock, Factions, SMP, Lifesteal, Prison, and more. Vote for your favorite server today."
      },
      servers: {
        title: "Minecraft Servers | Browse and Vote",
        description:
          "Browse Minecraft servers by players, votes, tags, and status. Find SMP, Skyblock, Factions, Lifesteal, Prison, PvP, and cross-play servers."
      },
      sponsored: {
        title: "Best Minecraft Servers | Icon Listing",
        description:
          "Discover sponsored Minecraft servers with highlighted placements, server details, live status, tags, trailers, and voting."
      },
      sponsoredClients: {
        title: "Best Minecraft Clients | Icon Listing",
        description:
          "Browse approved sponsored Minecraft clients with download links, videos, images, version support, and pricing details."
      }
    }
  },
  admins: {
    users: ["ItzKuroYT"],
    emails: ["isaaccooper926@gmail.com"]
  },
  limits: {
    bannerMaxBytes: 1048576,
    bannerMaxWidth: 468,
    bannerMaxHeight: 60,
    descriptionMinLength: 200,
    tagsMin: 1,
    tagsMax: 7,
    voteCooldownHours: 24,
    staleServerDeleteDays: 90
  },
  ranking: {
    playerWeight: 1,
    voteWeight: 8,
    sponsoredBoost: 100000
  },
  defaults: {
    javaPort: 25565,
    bedrockPort: 19132
  },
  sponsorship: {
    paypalRequired: true,
    applicationText:
      "To apply for sponsorship, join the Discord server and submit an application. Sponsorships are paid and currently require PayPal.",
    benefits: [
      "Top placement on the homepage.",
      "Top placement on matching tag pages.",
      "Top placement in search results.",
      "Highlighted listing style with a star badge."
    ]
  },
  copy: {
    nav: {
      home: "Home",
      servers: "Servers",
      sponsoredServers: "Sponsored",
      sponsoredClients: "Sponsored Clients",
      dashboard: "Dashboard",
      admin: "Admin",
      login: "Login"
    },
    empty: {
      title: "No servers listed yet",
      body: "Listings will show here after they are submitted and saved.",
      action: "Add a Server"
    },
    home: {
      eyebrow: "Minecraft server listing - done right.",
      title: "Icon Listing",
      body: "A simple place to list servers, check status, and vote. ",
      browseButton: "Browse servers",
      submitButton: "Submit a server",
      manageButton: "Manage listings",
      sponsoredTitle: "Sponsored Servers",
      sponsoredBody: "Paid placements. Marked separately from the main list.",
      allTitle: "All Servers",
      allBody: "Sorted by rank by default. Use search if you already know what you want."
    },
    servers: {
      title: "Servers",
      taggedTitleSuffix: "Servers",
      body: "Search by name, IP, or tag.",
      searchPlaceholder: "Search by name, IP, or tag"
    },
    sponsoredServers: {
      eyebrow: "Paid placements",
      title: "Sponsored Servers",
      body: "Sponsors get placement above normal results. The listing stays labeled so players know what they are looking at.",
      action: "Ask on Discord",
      benefitsTitle: "What sponsors get",
      applyTitle: "How to apply"
    },
    sponsoredClients: {
      title: "Sponsored Clients",
      body: "Client promotions approved by staff.",
      visitButton: "Website / Download",
      videoButton: "Watch video",
      freeLabel: "Free client",
      paidLabel: "Paid client"
    },
    login: {
      title: "Login",
      body: "Log in to manage your server listings.",
      signupPrompt: "Need an account?",
      signupLink: "Sign up below",
      signupTitle: "Sign Up",
      signupBody: "Create an account to submit a server."
    },
    dashboard: {
      loginRequired: "Log in to add and manage server listings.",
      title: "Dashboard",
      body: "Edit listings, check rank, or add another server.",
      addButton: "+ Add Server",
      settingsButton: "Account Settings"
    },
    admin: {
      accessRequired: "Admin access is required for this page.",
      title: "Admin Panel",
      body: "Manage servers, sponsorships, clients, users, and bans.",
      serverListingsTitle: "Server Listings",
      sponsoredClientsTitle: "Sponsored Clients",
      sponsoredClientsBody: "Create and edit sponsored Minecraft client listings.",
      noSponsoredClients: "No sponsored clients yet."
    },
    vote: {
      body: "Enter your Minecraft username so this vote can count on the monthly board.",
      emptyLeaderboard: "No monthly votes yet."
    },
    staticPages: {
      terms: ["Terms", "Use Icon Listing honestly. Do not submit listings you do not control, spam the vote system, or post unsafe content."],
      privacy: ["Privacy", "Icon Listing stores account details, listings, votes, and moderation data needed to run the site."],
      help: ["Help", "Need help with a listing, vote, sponsorship, or account? Join the Discord or contact the IconRealms team."],
      contact: ["Contact", "Reach IconRealms at officialfnaffanstudios@gmail.com or through Discord."]
    }
  },
  votifier: {
    enabled: true,
    providerEndpoint: "",
    documentationUrl: "https://github.com/NuVotifier/NuVotifier",
    testUsername: "IconListingTest"
  },
  moderation: {
    replacement: "***",
    blockedServerHosts: [
      "falixsrv.me",
      "falixserver.me",
      "aternos.me",
      "aternos.org"
    ],
    blockedWords: [
      "fuck",
      "shit",
      "bitch",
      "asshole",
      "bastard",
      "cunt",
      "dick",
      "pussy",
      "nigger",
      "nigga",
      "faggot",
      "retard",
      "kike",
      "spic",
      "chink",
      "coon",
      "tranny"
    ],
    blockedPatterns: [
      "n[i1!|][gq][gq][e3]r",
      "f[a@]gg[o0]t",
      "r[e3]t[a@]rd"
    ]
  },
  gamemodes: [
    "Survival",
    "Factions",
    "Skyblock",
    "Creative",
    "Anarchy",
    "OneBlock",
    "Economy",
    "PvP",
    "Pixelmon",
    "Lifesteal",
    "KitPvP",
    "Cobblemon",
    "SMP",
    "BoxPvP",
    "Roleplay",
    "Earth",
    "Prison",
    "RPG",
    "Towny",
    "Raiding",
    "Gens",
    "Farming",
    "Vanilla",
    "Minigames",
    "BedWars",
    "Parkour"
  ],
  generalTags: ["Bedrock", "Cross-Play", "Modded", "Whitelist", "New", "Old"],
  countries: [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo",
    "Costa Rica",
    "Cote d'Ivoire",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czechia",
    "Democratic Republic of the Congo",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Korea",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe"
  ],
  seedServers: [],
  sponsoredClients: []
};

if (typeof window !== "undefined") {
  window.ICON_LISTING_CONFIG = IconListingConfig;
}

if (typeof module !== "undefined") {
  module.exports = IconListingConfig;
}
